### ISSUE TITLE
Add dune file for Of_json

### ISSUE THREAD

**Issue by leviroth** [janestreet/jsonaf#1]
`Of_json` doesn't have a dune file, so it can't be compiled without modification.

**Comment by leviroth** [comment]
Sorry, I think I was looking at [jsonaf/of_json/dune](https://github.com/janestreet/jsonaf/blob/71278930ad481fc215399a209cbe29986d9ff816/of_json/dune) which is clearly a red herring. The real issue is that `Of_json` has no public name.

**Comment by aalekseyev** [comment]
Fixed, probably
